### ISSUE TITLE
Couldn't install transformers agent-planning branch

### ISSUE THREAD

**Issue by jimgoo** [aymeric-roucher/GAIA#3]
https://github.com/aymeric-roucher/GAIA/blob/4cd6b4bb58f3f5b6752dffa03440a460a61f6a79/requirements.txt#L26

I get this error:

```
 GAIA git:(main) pip install -r requirements.txt
Collecting git+https://github.com/huggingface/transformers.git[agents]@agents-planning (from -r requirements.txt (line 26))
  Cloning https://github.com/huggingface/transformers.git[agents] (to revision agents-planning) to /private/var/folders/kh/rpn06hk152n1vfrmxrcbw_0m0000gn/T/pip-req-build-1016li_s
  Running command git clone --filter=blob:none --quiet 'https://github.com/huggingface/transformers.git[agents]' /private/var/folders/kh/rpn06hk152n1vfrmxrcbw_0m0000gn/T/pip-req-build-1016li_s
  remote: Repository not found.
  fatal: repository 'https://github.com/huggingface/transformers.git[agents]/' not found
```

**Comment by magucas** [comment]
@jimgoo @aymeric-roucher 
Hi, Jimgoo, did you get some useful methods to finish this problem?

I'm installing the pakage listed in requirements also find the "git+https://github.com/huggingface/transformers.git[agents]@agents-planning" can not be git clone. Because this repository is not existed now.

I genuinely appreciate your help and support if you share me your any good solutions to solve this problem.

**Comment by malusheng** [comment]
@aymeric-roucher 
I had the same problem when installing.

Running command git clone --filter=blob:none --quiet 'https://github.com/huggingface/transformers.git[agents]'
  remote: Repository not found.
  fatal: repository 'https://github.com/huggingface/transformers.git[agents]/' not found
  error: subprocess-exited-with-error

**Comment by aymeric-roucher** [comment]
Hello all,
Apologies, the `requirements.txt` file pointed out to an older branch which is now deleted after having been merged into the main repo. Now I've just pushed a change which should correct this!
